List features = [
{
  "id" : 99,
  "name" : "Why Adopt a Special Needs Child?",
  "image" : "https://orphancare.org.my/wp-content/uploads/2021/10/adopt-a-special-needs-child-1536x1024.jpg",
  "price" : "Read More..",
  "duration" : "-",
  "session" : "-",
  "review" : "5",
  "is_favorited" : false,
  "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
},
{
  "id" : 100,
  "name" : "Why Adopt an Older Child?",
  "image" : "https://orphancare.org.my/wp-content/uploads/2021/10/adopt-an-older-child-1536x1024.jpg",
  "price" : "Read More..",
  "duration" : "-",
  "session" : "-",
  "review" : "4.5",
  "is_favorited" : false,
  "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
},
  {
    "id" : 101,
    "name" : "Our Stories",
    "image" : "https://orphancare.org.my/wp-content/uploads/2021/07/Baby-hatch.png",
    "price" : "Read More..",
    "duration" : "",
    "session" : "-",
    "review" : "5",
    "is_favorited" : true,
    "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  },
  {
    "id" : 102,
    "name" : "An Adoption Story",
    "image" : "https://orphancare.org.my/wp-content/uploads/2021/10/an-adoption-story-scaled-e1634727705856-1536x1363.jpg",
    "price" : "Read More..",
    "duration" : "-",
    "session" : "-",
    "review" : "4.5",
    "is_favorited" : false,
    "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  },
  {
    "id" : 103,
    "name" : "Sexual Health Rights and Responsibilities",
    "image" : "https://orphancare.org.my/wp-content/uploads/2021/11/rh-i-am-in-control-1536x1024.jpeg",
    "price" : "Read more..",
    "duration" : "-",
    "session" : "-",
    "review" : "4.5",
    "is_favorited" : false,
    "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  },
  {
    "id" : 104,
    "name" : "History of Baby Hatches",
    "image" : "https://orphancare.org.my/wp-content/uploads/2022/01/history-of-baby-hatches-1536x1024.jpg",
    "price" : "Read more..",
    "duration" : "-",
    "session" : "-",
    "review" : "5",
    "is_favorited" : false,
    "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  },
];

List recommends = [
  {
    "id" : 105,
    "name" : "Petaling Jaya",
    "image" : "https://www.pngitem.com/pimgs/m/568-5688113_transparent-png-phone-icons-pink-phone-icon-png.png",
    "price" : "010 283 0528",
    "duration" : "24/7 hours",
    "session" : "-",
    "review" : "-",
    "is_favorited" : false,
    "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  },
  {
    "id" : 106,
    "name" : "Johor Bahru",
    "image" : "https://www.pngitem.com/pimgs/m/568-5688113_transparent-png-phone-icons-pink-phone-icon-png.png",
    "price" : "019 726 2368",
    "duration" : "24/7",
    "session" : "-",
    "review" : "-",
    "is_favorited" : false,
    "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  },
  {
    "id" : 107,
    "name" : "Sungai Petani",
    "image" : "https://www.pngitem.com/pimgs/m/568-5688113_transparent-png-phone-icons-pink-phone-icon-png.png",
    "price" : "04 442 3900",
    "duration" : "24/7",
    "session" : "-",
    "review" : "-",
    "is_favorited" : false,
    "description" : "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  }
];



List chats = [
    {
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp3ruOVN7HR0x-aJhh7VypWmSmgcsBSfIbBQ&usqp=CAU",
    "fname" : "Kedah baby hatch",
    "lname" : "Sungai Petani",
    "name": "Kedah baby hatch",
    "skill": "5.6541141",
    "last_text": "[Sungai Petani]",
    "date": "100.5192692",
    "notify" : 0,
  },
  {
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp3ruOVN7HR0x-aJhh7VypWmSmgcsBSfIbBQ&usqp=CAU",
    "fname" : "Johor baby hatch",
    "lname" : "Sungai Petani",
    "name": "Johor baby hatch",
    "skill": "1.4953756",
    "last_text": "[Johor Bharu]",
    "date": "103.7710573",
    "notify" : 0,
  },
  {
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp3ruOVN7HR0x-aJhh7VypWmSmgcsBSfIbBQ&usqp=CAU",
    "fname" : "Selangor baby hatch",
    "lname" : "Sungai Petani",
    "name": "Selangor baby hatch",
    "skill": "3.0904853",
    "last_text": "[Petaling Jaya]",
    "date": "101.6550649",
    "notify" : 0,
  },
];